### ISSUE TITLE
Impl JsonSchema for for rocket_validation::Validated

### ISSUE THREAD

**Issue by auipga** [GREsau/schemars#243]
I'm struggling to implement [rocket_validation::Validated](https://docs.rs/rocket-validation/0.1.3/rocket_validation/struct.Validated.html).

Could sb. please guide me to the right direction?

By reading #187 I've come this far:

`Cargo.toml`:
```toml
[dependencies.rocket-validation]
version = "0.1.3"
optional = true
```

`src/json_schema_impls/mod.rs`:
```Rust
#[cfg(feature = "rocket-validation")]
mod rocket_validation;
```

`src/json_schema_impls/rocket_validation.rs`:
```Rust
forward_impl!(rocket_validation::Validated<something> => something);
```
where `something` could be `rocket::serde::json::Json<T>` or just `T`
