### ISSUE TITLE
Incorrect schema for flattened optional untagged enum

### ISSUE THREAD

**Issue by Masken8** [GREsau/schemars#367]
```rs
use schemars::{schema_for, JsonSchema};
use serde::{Deserialize, Serialize};

fn main() {
    let schema = schema_for!(Root);
    let schema = serde_json::to_value(&schema).unwrap();
    let validator = jsonschema::validator_for(&schema).unwrap();
    let json = serde_json::json!({
        "blah": "Foo"
    });
    let result = validator.validate(&json).unwrap(); // called `Result::unwrap()` on an `Err` value: ValidationError { instance: Object {"blah": String("Foo")}, kind: AnyOf, instance_path: Location(""), schema_path: Location("/anyOf") }
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct BarAndBaz {
    pub bar: String,
    pub baz: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct Bar {
    pub bar: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
#[serde(untagged)]
pub enum Foo {
    BarAndBaz(BarAndBaz),
    Bar(Bar),
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct Root {
    #[serde(flatten)]
    pub foo: Option<Foo>,

    pub blah: String,
}
```
```toml
[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.135"
schemars = { version = "=1.0.0-alpha.17" }
jsonschema = "0.28.1"
```
